Repository jenkinsci/throttle-concurrent-builds-plugin, pull requests merged in 2024-10, with the labels that each got.

#271 Require Java 17 or newer; migrate to EE 9
  pom.xml
  src/main/java/hudson/plugins/throttleconcurrents/ThrottleJobProperty.java
  src/test/java/hudson/plugins/throttleconcurrents/ThrottleJobPropertyPipelineTest.java
  src/test/java/hudson/plugins/throttleconcurrents/ThrottleStepTest.java
Labels: internal

#232 [JENKINS-67978] Fix for job parameters on built-in node
  src/main/java/hudson/plugins/throttleconcurrents/ThrottleQueueTaskDispatcher.java
Labels: bug

#197 Reduce use of `workflow-durable-task-step` dep through `SubTask.getOwnerExecutable`
  pom.xml
  src/main/java/hudson/plugins/throttleconcurrents/ThrottleQueueTaskDispatcher.java
Labels: internal

#277 Require 2.479.1 LTS or newer
  pom.xml
Labels: skip-changelog
